-- Current development schema for Job Radar.
-- Generated by `just migrations-squash`.
-- During early development this migration is intentionally squashed instead of
-- keeping a history of intermediate schema experiments.

CREATE TABLE app_metadata(
  key TEXT PRIMARY KEY NOT NULL,
  value TEXT NOT NULL
);

CREATE TABLE app_settings(
  key TEXT PRIMARY KEY NOT NULL,
  value_json TEXT NOT NULL DEFAULT 'null',
  updated_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CHECK(json_valid(value_json))
);

CREATE TABLE search_requests(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  status TEXT NOT NULL,
  include_rules_json TEXT NOT NULL DEFAULT '[]',
  exclude_rules_json TEXT NOT NULL DEFAULT '[]',
  locations_json TEXT NOT NULL DEFAULT '[]',
  radius_km INTEGER NULL,
  source_keys_json TEXT NOT NULL DEFAULT '[]',
  validation_error TEXT NULL,
  created_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  CHECK(status IN('draft', 'active', 'disabled', 'invalid')),
  CHECK(json_valid(include_rules_json)),
  CHECK(json_valid(exclude_rules_json)),
  CHECK(json_valid(locations_json)),
  CHECK(json_valid(source_keys_json)),
  CHECK(radius_km IS NULL OR radius_km >= 0)
);
