#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
migrations_dir="${MIGRATIONS_DIR:-$repo_root/src-tauri/migrations}"

case "$migrations_dir" in
  /*) ;;
  *) migrations_dir="$repo_root/$migrations_dir" ;;
esac

if ! command -v sqlite3 >/dev/null 2>&1; then
  echo "sqlite3 is required to squash migrations." >&2
  exit 1
fi

if [[ ! -d "$migrations_dir" ]]; then
  echo "Migrations directory not found: $migrations_dir" >&2
  exit 1
fi

migrations=()
for migration in "$migrations_dir"/*.sql; do
  [[ -e "$migration" ]] || continue
  migrations+=("$migration")
done

if [[ "${#migrations[@]}" -eq 0 ]]; then
  echo "No .sql migrations found in $migrations_dir" >&2
  exit 1
fi

IFS=$'\n' sorted_migrations=($(printf '%s\n' "${migrations[@]}" | sort))
unset IFS
migrations=("${sorted_migrations[@]}")

target="${1:-${migrations[0]}}"
case "$target" in
  /*) ;;
  *) target="$repo_root/$target" ;;
esac
mkdir -p "$(dirname "$target")"

target_abs="$(cd "$(dirname "$target")" && pwd)/$(basename "$target")"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

tmp_db="$tmp_dir/schema.db"
schema_sql="$tmp_dir/schema.sql"
next_target="$tmp_dir/$(basename "$target_abs")"

for migration in "${migrations[@]}"; do
  echo "applying: ${migration#$repo_root/}"
  {
    printf '.bail on\n'
    printf 'PRAGMA foreign_keys = ON;\n'
    cat "$migration"
  } | sqlite3 "$tmp_db"
done

sqlite3 "$tmp_db" <<'SQL' | grep -v '^CREATE TABLE sqlite_sequence' > "$schema_sql"
.bail on
.schema --indent
SQL

cat > "$next_target" <<'HEADER'
-- Current development schema for Job Radar.
-- Generated by `just migrations-squash`.
-- During early development this migration is intentionally squashed instead of
-- keeping a history of intermediate schema experiments.

HEADER
cat "$schema_sql" >> "$next_target"

cp "$next_target" "$target_abs"

removed=0
for migration in "${migrations[@]}"; do
  migration_abs="$(cd "$(dirname "$migration")" && pwd)/$(basename "$migration")"
  if [[ "$migration_abs" != "$target_abs" ]]; then
    rm -f -- "$migration_abs"
    echo "removed: ${migration_abs#$repo_root/}"
    removed=1
  fi
done

echo "squashed ${#migrations[@]} migration(s) into: ${target_abs#$repo_root/}"
if [[ "$removed" == "1" ]]; then
  echo "Existing databases that already ran old migrations must be cleared before startup."
fi
